FizzBuzz問題の課題
gorinesia/test1 pull request #1
Opened 2020-06-03 01:01 UTC by gorinesia

JavaScriptでDOM操作、if文、for文、関数を使って、課題に取り組みました。

DOM操作の基本を学ぶのに最適な課題だと思います。

エラー文にはif文、fizzbuzzの式にはfor文、値を表示させるためにDOMを操作しました。

関数は、”エラー文を表示させるため”、”値を空にするため”に２つ作りました。

・if文は関数など重複している部分があるので、もっと短く書けるのでは、と思いました。

・２つの関数をまとめることも考えましたが、正常に実行された場合の処理が上手くいかないため、
関数を２つにして管理しています。

以上の点はなにか改善できる点があるかと思いますが、いかがでしょうか？

2020-06-03 14:44 UTC, myzktkyk requested changes
何点かバグと思われる箇所がありますので指摘をしました。
ご確認お願いします。

2020-06-03 14:44 UTC, myzktkyk commented on main.js
> +  if (isNaN(fizzes && buzzes)) {
なさりたかったことは
「 `fizzes` と ` buzzes` のどちらかに数字でないものが入っていたらエラー」
と思うのですが、このコードだとそれが実現できていません。

`isNaN(fizzes) || isNaN(buzzes)` としてみてください。

2020-06-03 14:44 UTC, myzktkyk commented on main.js
> +  if (fizzes.match(/^-?[0-9]+\.[0-9]+$/) && buzzes.match(/^-?[0-9]+\.[0-9]+$/)) {
正規表現を使われていてすごくいいと思います！
…ですが `&&` では正しい判定ができない（ `&&` だと *どちらも* 小数の場合だけエラーになる）ので
`||` を使用してください。

2020-06-03 14:46 UTC, myzktkyk commented
>if文は関数など重複している部分があるので、もっと短く書けるのでは、と思いました。

せっかく正規表現を使われているので
例えば正規表現だけで「整数かどうか」をチェックしてはいかがでしょう？
そうすれば値の検証のためのコードが大きく減らせると思います。

2020-06-03 20:29 UTC, takuyeaaaah approved these changes
コメントいくつかしたけれど、俺のコメント箇所は正直直しても直さなくてもプログラムには影響はないからあとは @myzktkyk さんが指摘してる箇所を直せばまずは問題ないと思うよー 🙆‍♂️

2020-06-03 20:29 UTC, takuyeaaaah commented on index.html
> +  <p>BuzzNum:<input type="text" name="buzzes" id="buzz" placeholder="整数値を入力してください"></p>
[nits] 好みの世界ではあるから特に直す必要はないけれど、nameをもっと明示的にかいてもいいかもね〜

```diff
- fizzes
+ fizzNum
```

```diff
- buzzes
+ buzzNum
```

2020-06-03 20:29 UTC, takuyeaaaah commented on index.html
> +  </script>
[nits] srcで参照するだけで中身がないscriptタグは1行でかいてしまっていいと思う
```
<script src="main.js"></script>
```

2020-06-03 20:29 UTC, takuyeaaaah commented on main.js
> +  const buzzes = buzzNumber.value;
[nits] ここも細かい部分&処理は問題がないから参考までにって感じだけれど、

> const fizzNumber = document.getElementById('fizz');

この `fizzNumber` という変数には数値ではなくて `document.getElementById('fizzNumber')` という `fizzNumber` が含まれているエレメントが代入されているから `elemFizzNumber` とかで定義しして、 `elemFizzNumber.value` を代入する先が `fizzNumber` にしてあげると見通しがいい(あとあと読みやすい)かも〜

```
const elemFizzNumber = document.getElementById('fizz');
const fizzeNumber = elemFizzNumber.value;
```

2020-06-03 20:29 UTC, takuyeaaaah commented on main.js
> +    }
[FYI] DRYな感じにこうかいたりもできるかもー
```
let message = ‘’;
if (i % fizzes == 0) message += 'Fizz';
if (i % buzzes == 0) message += 'Buzz';
if (message.length > 0) fizzbuzz.textContent = `${message} ${i}`;
```

2020-06-03 20:29 UTC, takuyeaaaah commented on main.js
> +  }
この課題だけだと明確な仕様が出ていないけれど、
バリデーション(入力値のチェック)は

- 空欄だった時
- 文字列が入力された時
- 少数が入力された時

の順番で処理をかいて、
無効な値が入ってきた時点で処理を抜けてしまうのがいいと思うよー

空欄だったら->文字列でも少数でもない
文字列だったら->少数ではない

https://www.notion.so/JavaScript-d4e2e356109c41148870225f46fe5baf

2020-06-03 22:26 UTC, gorinesia commented on main.js
> +  if (isNaN(fizzes && buzzes)) {
承知しました。
両方にisNaNをつけてもいいんですね、やってみます！

2020-06-03 22:27 UTC, gorinesia commented on main.js
> +  if (fizzes.match(/^-?[0-9]+\.[0-9]+$/) && buzzes.match(/^-?[0-9]+\.[0-9]+$/)) {
はい、こちらもすぐ変えます！

2020-06-03 22:27 UTC, gorinesia commented on index.html
> +  </script>
なるほど、参考になります！

2020-06-03 23:51 UTC, gorinesia commented on index.html
> +  <p>BuzzNum:<input type="text" name="buzzes" id="buzz" placeholder="整数値を入力してください"></p>
明示的にですか、大事な感覚ですね！
参考になります！

2020-06-03 23:54 UTC, gorinesia commented on main.js
> +  const buzzes = buzzNumber.value;
あー、なるほど、とても参考になります！
読む人に対しても意味が伝わるように書かないといけませんね！
ありがとうございます！

2020-06-03 23:55 UTC, gorinesia commented on main.js
> +    }
すごい、そんな感じで表したり出来るんですか、
やってみます！

2020-06-03 23:59 UTC, gorinesia commented on main.js
> +  }
そうやって定義して書いていけば、
if文に何回も同じことを書かなくても出来そうですね！
もう少しやってみます！
ありがとうございます！

2020-06-04 13:41 UTC, gorinesia reviewed
訂正のコメントありがとうございました！
簡単に修正できる箇所は修正しました。
正規表現だけで「整数かどうか」をチェックするのはまだ難しく、すぐには形にできない状況です。
よろしくお願いいたします。

2020-06-04 13:41 UTC, gorinesia commented on main.js
> +  if (isNaN(fizzNumber) || isNaN(buzzNumber)) {
&&を||に変更しました。

2020-06-04 13:41 UTC, gorinesia commented on main.js
> +  if (fizzNumber.match(/^-?[0-9]+\.[0-9]+$/) || buzzNumber.match(/^-?[0-9]+\.[0-9]+$/)) {
&&を||に変更しました。

2020-06-04 13:41 UTC, gorinesia commented on main.js
> +  const buzzNumber = elemBuzzNumber.value;
定数名を明示的にわかりやすくするために変更しました。
・fizzNumber→elemFizzNumber
・fizzes→fizzNumber
・buzzNumber→elemBuzzNumber
・buzzes→BuzzNumber

2020-06-05 04:21 UTC, myzktkyk approved these changes
修正点を確認させていただきました。問題ないと思います！

2020-06-05 12:14 UTC, gorinesia commented
@myzktkyk 
ご確認ありがとうございます！
問題なければマージさせていただきますが、いかがでしょうか？

2020-06-05 12:33 UTC, gorinesia commented
@takuyeaaaah 
 的確なアドバイスありがとうございました。
すぐに修正できる箇所はしました。

2020-06-05 15:26 UTC, myzktkyk commented
@gorinesia はい、Mergeしていだいて結構です！

2020-06-06 00:23 UTC, merged